version: '3'
services:
  scrapper:
    build: ./scrapper
    links:
      - mongo
  web:
    build: ./web
    ports:
        - "5000:5000"
    links:
      - mongo
  mongo:
    image: "mongo"
    ports:
        - "27017:27017"
